"""Global macro dashboard panel — self-contained HTML.

Renders outputs/international/index.html: one card per region with the
latest CPI / core CPI / GDP / unemployment / policy-rate readings. Mirrors
the US dashboard's inline-CSS, static-deploy style so it slots into the
same GitHub Pages site.
"""

from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

from ..outputs import outputs_root
from .config import INDICATOR_LABELS, INDICATOR_ORDER, REGION_LABELS, REGION_ORDER
from .format import fmt_change, fmt_period, fmt_value
from .model import IntlSeriesResult

ET = ZoneInfo("America/New_York")


def render_dashboard(
    results: list[IntlSeriesResult], output_path: Path | None = None
) -> Path:
    if output_path is None:
        output_path = outputs_root() / "international" / "index.html"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    cards = [_render_card(results, region) for region in REGION_ORDER]
    ok = sum(1 for r in results if r.ok)
    html_text = _TEMPLATE.format(
        generated_at=datetime.now(ET).strftime("%a %b %d %Y %H:%M ET"),
        ok=ok,
        total=len(results),
        cards="\n".join(c for c in cards if c),
    )
    output_path.write_text(html_text, encoding="utf-8")
    return output_path


def _render_card(results: list[IntlSeriesResult], region: str) -> str:
    in_region = [r for r in results if r.region == region]
    if not in_region:
        return ""
    order = {ind: i for i, ind in enumerate(INDICATOR_ORDER)}
    in_region.sort(key=lambda r: order.get(r.indicator, 99))

    rows = []
    for r in in_region:
        label = html.escape(INDICATOR_LABELS.get(r.indicator, r.indicator))
        if r.ok:
            delta = fmt_change(r)
            cls = "up" if delta.startswith("▲") else ("down" if delta.startswith("▼") else "")
            delta_html = f"<span class='delta {cls}'>{html.escape(delta)}</span>" if delta else ""
            rows.append(
                f"<div class='row'><span class='lbl'>{label}</span>"
                f"<span class='val'>{html.escape(fmt_value(r))}{delta_html}"
                f"<span class='per'>{html.escape(fmt_period(r.latest.period))}</span></span></div>"
            )
        else:
            why = "needs API key" if "APP_ID" in (r.error or "") else "unavailable"
            rows.append(
                f"<div class='row nodata'><span class='lbl'>{label}</span>"
                f"<span class='val'>—<span class='per'>{why}</span></span></div>"
            )
    return (
        f"<div class='card'><h2>{html.escape(REGION_LABELS.get(region, region))}</h2>"
        + "".join(rows)
        + "</div>"
    )


_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Global macro — current state</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
          max-width: 1100px; margin: 1em auto; padding: 0 1em; color: #222; background: #fafafa; }}
  h1 {{ font-size: 1.6em; margin-bottom: 0.1em; }}
  .subtitle {{ color: #666; margin-bottom: 1.5em; font-size: 0.95em; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(330px, 1fr)); gap: 1em; }}
  .card {{ background: white; border-radius: 6px; padding: 1em 1.2em; border: 1px solid #e0e0e0; }}
  .card h2 {{ font-size: 1.1em; margin: 0 0 0.5em 0; color: #1F4E79; }}
  .row {{ display: flex; justify-content: space-between; align-items: baseline;
          padding: 0.35em 0; border-bottom: 1px solid #f2f2f2; }}
  .row.nodata .val {{ color: #aaa; }}
  .lbl {{ font-size: 0.9em; color: #555; }}
  .val {{ font-variant-numeric: tabular-nums; font-weight: 600; text-align: right; }}
  .delta {{ font-size: 0.75em; font-weight: 600; margin-left: 0.4em; }}
  .delta.up {{ color: #C0392B; }}
  .delta.down {{ color: #1E8449; }}
  .per {{ display: block; font-size: 0.7em; color: #999; font-weight: 400; }}
  .footer {{ font-size: 0.8em; color: #888; margin-top: 2em; padding-top: 1em; border-top: 1px solid #e0e0e0; }}
</style>
</head>
<body>
<h1>🌍 Global macro — current state</h1>
<p class="subtitle">Latest international readings ({ok}/{total} series). Generated {generated_at}.</p>
<div class="grid">
{cards}
</div>
<div class="footer">
  Sources: Eurostat · ECB · ONS · BoE · OECD · e-Stat · FRED.
  Generated by <code>macro_monitor.international.dashboard</code>. Δ = change vs prior reading.
</div>
</body>
</html>
"""
